[package]
name = "sysdump"
version = "0.1.0"
edition = "2021"
authors = ["shellrow <81893184+shellrow@users.noreply.github.com>"]

[dependencies]
default-net = "0.8.0"
sysinfo = "0.23.0"
netstat2 = "0.9.1"
term-table = "1.3.2"
